---
#_target_: flwr.server.strategy.FedAvg
_target_: short_term_load_forecasting.server.FedAvgSaveModel
fraction_fit: 0.01 # Sample 1% of available clients for training
fraction_evaluate: 0.01 # Sample 1% of available clients for evaluation
min_fit_clients: ${num_clients_per_round}  # Never sample less than n clients for training
min_evaluate_clients: ${num_clients_per_round}  # Never sample less than n clients for evaluation
min_available_clients: ${num_clients}  # Wait until all n clients are available